### DPF contract ###
serviceDaemonSet:
  nodeSelector:
  labels: {}
  annotations: {}
  updateStrategy: {}
  resources: {}
exposedPorts:
  labels: {}
  ports: {}

### Service specific values ###
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
podSecurityContext: {}
securityContext: {}
tolerations: []
