apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carbide-otelcol.fullname" . }}-config
  labels:
    {{- include "carbide-otelcol.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Files.Get "files/otel_config.yaml" | nindent 4 }}
