apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carbide-dpu-otel-agent.fullname" . }}-config
  labels:
    {{- include "carbide-dpu-otel-agent.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Files.Get "files/otel-agent-config.toml" | nindent 4 }}
